import commands.api
import commands.chat
import commands.debug
import commands.event
import commands.kjell
import commands.link
import commands.random
import commands.skatt
import commands.time
import commands.kalender
import commands.paminn
import commands.vader
import commands.rost
import commands.triggers
